### ISSUE TITLE
landing page and UI tweaks

### ISSUE THREAD

**Issue by sebastianovide** [Geovation/photos#11]
New UI/UX based on material UI

**Comment by kdalkafoukis** [comment]
I am waiting for @challdesign to make UI/UX decisions

**Comment by kdalkafoukis** [comment]
The landing page has been delivered
I'm waiting only for  the UI/UX tweaks

**Comment by sebastianovide** [comment]
@kdalkafoukis  anything else left here ?

**Comment by sebastianovide** [comment]
after Rob design being slitted in different tickets, I can close this
