### ISSUE TITLE
open an external page inside an IFrame

### ISSUE THREAD

**Issue by sebastianovide** [Geovation/photos#3]
We know about some customers embedding maps. So as first step, it will allow us to insert an existing map coming from a different server.

**Comment by kdalkafoukis** [comment]
After discussion with @GeovationMax we have decided to show a map based on OS Open Zoomstack instead of an iFrame.

Reasons :
- most websites are protected from being embedded as iFrame
- better user experience
- reasons for using an iFrame were not clear
