### ISSUE TITLE
validate email

### ISSUE THREAD

**Issue by sebastianovide** [Geovation/photos#371]

**Comment by sebastianovide** [comment]
merged. @globalavocado do you want to test it ? if you like it you could use it in plastic patrol

**Comment by globalavocado** [comment]
have merged and will test now.

**Comment by globalavocado** [comment]
merged locally first.

**Comment by sebastianovide** [comment]
review the message. and the UI. It seems different than the rest of the application and it doesn't explain clearly that the app cannot be used until when the email has been validated.

**Comment by YousafAzabi** [comment]
in #395
