### ISSUE TITLE
account is showing the wrong photos

### ISSUE THREAD

**Issue by sebastianovide** [Geovation/photos#561]
it shows also photos that have not been approved

**Comment by samsammurphy** [comment]
The demo data created by [populateDemoData.js](https://github.com/Geovation/photos/blob/179ec9c47840212d39698023c28c3c8c24213776/scripts/populateDemoData.js#L54) seems to be uploaded to a hardcoded storage bucket location

`storageBucket: "photos-demo-d4b14.appspot.com"`

As opposed to reading it from, for example, [config.dev.json](https://github.com/Geovation/photos/blob/179ec9c47840212d39698023c28c3c8c24213776/src/custom/config.dev.json#L8).

This might be causing an issue (at least in forked repos)

**Comment by samsammurphy** [comment]
p.s. also, I am a little confused as to why the storageBucket seems to be a Google App Engine

**Comment by sebastianovide** [comment]
ok... there are 3 different problems in the ticket... Need to be splitter
