### ISSUE TITLE
npm install modifies package-lock.json

### ISSUE THREAD

**Issue by samsammurphy** [Geovation/photos#565]
Installing node modules using `npm install` will modify package-lock.json, this will create a code clash if commited to forked repo in an unexpected way as it is outside of the designated src/custom folder

suggested alternative is to use [npm ci](https://docs.npmjs.com/cli/ci) as recommended [here](https://stackoverflow.com/questions/48524417/should-the-package-lock-json-file-be-added-to-gitignore)

npm ci does not update package-lock.json

**Comment by sebastianovide** [comment]
done in #566
