### ISSUE TITLE
.gitignore README.md

### ISSUE THREAD

**Issue by samsammurphy** [Geovation/photos#569]
The README.md is perhaps the only file that needs to be customizable BUT should not be inside src/custom/

If forked code updates the README.md it will create a merge conflict (!)

**Suggested solution**
1. Untrack the README.md

`git rm README.md`

2.  add it to `.gitignore`

**Potential issues**
Users would have to update README.md online only using github. Personally it is what I do normally because it is easy to preview the markdown. Not sure if that would work for everyone but cannot think of a better solution off the top of my head.

**Comment by sebastianovide** [comment]
I don't get it. This file is intended to be for the Geovation Photos. What about creating a custom doc folder ? or a custom read me ? README-custom.md ?

**Comment by samsammurphy** [comment]
It was not a good suggestion. Closing the issue..

My understanding is github requires a README.md in the root directory of a repo so that it can render that information online in the repo webpage. 

Each fork of Geovation/Photos will have its own README.md. Our setup is to pull code from Geovation/photos to Earthscope/photos. This could create a merge conflict.

However, untracking README.md will not work because it will be tracked again as soon as anyone makes a change to it online.
