### ISSUE TITLE
Firebase config

### ISSUE THREAD

**Issue by samsammurphy** [Geovation/photos#571]
I am trying to configure Photos to use my new firebase project.

The [config.dev.json](https://github.com/Geovation/photos/blob/master/src/custom/config.dev.json) file contains the dev environment configuration variables.

The FIREBASE object in that config file contains two properties (`apiURL` and `publicVapidKey`) 

![config dev json](https://user-images.githubusercontent.com/16657983/85845674-87d6bd80-b79c-11ea-90fc-5759798aa9b1.png)

that are not included in the config settings of my new firebase webapp

![firebase_config](https://user-images.githubusercontent.com/16657983/85845535-4fcf7a80-b79c-11ea-9068-70a71bf7ad60.png)

Can I use the old variables for now?

**Comment by samsammurphy** [comment]
UPDATE.

Steps I tried so far
1.  New Firebase Project (`earthscope-photos`)
2.  New web app (`webapp`)
3.  config.dev.json updated

Resulted in
authentication error

This is the browser alert..
![firebase_broken_config](https://user-images.githubusercontent.com/16657983/85860645-05a7c280-b7b7-11ea-9eb1-3e604f59b5d3.png)

and here is the develop console..
![firebase_broken_config2](https://user-images.githubusercontent.com/16657983/85860653-08a2b300-b7b7-11ea-8b04-3047c3a37766.png)

**Comment by sebastianovide** [comment]
ok. It makes sense to move those two keys outside "FIREBASE" so that it would be possible to copy and paste from firebase console

**Comment by sebastianovide** [comment]
@samsammurphy what about https://github.com/Geovation/photos/pull/573 ?

**Comment by sebastianovide** [comment]
I've also created #574
