### ISSUE TITLE
Photo upload not checking for geotag

### ISSUE THREAD

**Issue by samsammurphy** [Geovation/photos#578]
There was previously a check to see if the photo was geotagged on upload. I can now upload a photo for moderation without it having a geotag and without receiving a warning.

For example, [this photo](https://en.wikipedia.org/wiki/Tree#/media/File:Ash_Tree_-_geograph.org.uk_-_590710.jpg
) from wikipedia (uploaded today)

**Comment by sebastianovide** [comment]
ooo... really ? that is a bug.. Let me label it

**Comment by sebastianovide** [comment]
@samsammurphy I cannot reproduce it. Can you add a linik to the image that you are using ?
