### ISSUE TITLE
allow Photo upload without fields

### ISSUE THREAD

**Issue by samsammurphy** [Geovation/photos#579]
Users required to fill three separate fields for every photo upload

![photo_upload](https://user-images.githubusercontent.com/16657983/86255878-931c5580-bbaf-11ea-9b1a-ac8c0103be75.png)

For the Earthscope use case none of these fields are required (not even the description) as we will have a professional in-house ecologists to describe the photo.

From a UX I also really want to make photo upload as easy as possible (e.g. no text fields or drop down menus).

**Comment by sebastianovide** [comment]
this is configurable. You can add or remove fields.... See https://github.com/Geovation/photos/blob/master/src/custom/config.js#L140.

**Comment by sebastianovide** [comment]
removing the fields, it throw an error. That's a bug. In the mean time, you will need to add at least 1 field.

**Comment by sebastianovide** [comment]
@samsammurphy can you check if it works for you ? you just need to replace `PHOTO_FIELDS : {....` with `PHOTO_FIELDS: {}`
